include:
  - project: kount/third_party/tpa-ci-shared
    file:
      - core/rules.yml
      - version.yml
      - base/sq-scan.yml
    ref: 2.7.1

stages:
  - version
  - build
  - test
  - sonarqube scan
  - deploy

variables:
  #MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"
  GPG_CLI_OPTS: "--pinentry-mode loopback"
  # GPG_PASSPHRASE: ${GPG_PASSPHRASE}

.maven:
  image: maven:amazoncorretto
  before_script:
    - echo ${SONATYPE_USERID}
    - echo "$GPG_KEY" > private_key_sender.asc
    - chmod 400 ./private_key_sender.asc
    - echo '<?xml version="1.0" encoding="UTF-8"?><settings><servers><server><id>ossrh</id><username>'${SONATYPE_USERID}'</username><password>'${SONATYPE_PASSWORD}'</password></server></servers><profiles><profile><activation><activeByDefault>true</activeByDefault></activation><id>ossrh</id><properties><gpg.executable>gpg</gpg.executable><gpg.passphrase>'${GPG_PASSPHRASE}'</gpg.passphrase></properties></profile></profiles></settings>' > settings.xml
    - chmod 400 ./settings.xml
    - yum install -y openssl
    - |
      if [ -n "${BUILD_VERSION}" ]
      then
        # BUILD_VERSION is cut to 17 characters so SDK_VERSION will not exceed 32 characters in total
        BUILD_VERSION=`echo $BUILD_VERSION | cut -c-17`
        echo "sed -i \"s/0.0.0/${BUILD_VERSION}/g\" ${CI_PROJECT_DIR}/kount-ris-sdk/src/main/java/com/kount/ris/Config.java"
        sed -i "s/0.0.0/${BUILD_VERSION}/g" ${CI_PROJECT_DIR}/kount-ris-sdk/src/main/java/com/kount/ris/Config.java
        cat ${CI_PROJECT_DIR}/kount-ris-sdk/src/main/java/com/kount/ris/Config.java
        POM_VERS=`echo $BUILD_VERSION`
        if grep -q "-" <<< "$BUILD_VERSION";
        then
          BASE_VERS=`echo "$BUILD_VERSION" | sed 's/-.*//'`
          NEXT_VERS=`echo "$BASE_VERS" | awk -vFS=. -vOFS=. '{++$NF;print}'`
          POM_VERS="$NEXT_VERS-SNAPSHOT"
        fi
        echo ${POM_VERS}
        mvn versions:set -DnewVersion=${POM_VERS}
        mvn versions:update-child-modules
      fi
    - |
        if [ -n "${PAYMENTS_FRAUD_API_ENDPOINT}" ]
        then
          HOST_NAME=$(echo ${PAYMENTS_FRAUD_API_ENDPOINT} | sed 's/https:\/\///' | sed 's/\//\//' | sed 's/\/.*//')
          KEYSTORE_PATH=$JAVA_HOME/lib/security/cacerts
          
          # Download the certificate
          echo "Downloading certificate from $HOST_NAME..."
          # openssl s_client -servername $HOST_NAME -connect $HOST_NAME:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > temp.crt
          openssl s_client -showcerts -verify 5 -connect $HOST_NAME:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > temp.crt
          
          if [ -s "temp.crt" ]; then
          echo "Certificate downloaded successfully."
          else
          echo "Failed to download certificate."
          exit 1
          fi
          
          # Add the certificate to the keystore
          echo "Adding certificate to keystore '$KEYSTORE_PATH' with alias '$HOST_NAME'..."
          keytool -import -trustcacerts -alias "$HOST_NAME" -file "temp.crt" -keystore "$KEYSTORE_PATH" -noprompt
          
          if [ $? -eq 0 ]; then
          echo "Certificate added to keystore successfully."
          else
          echo "Failed to add certificate to keystore."
          fi
          rm temp.crt
        fi

        HOST_NAME='risk.test.kount.net'
        KEYSTORE_PATH=$JAVA_HOME/lib/security/cacerts
      
        # Download the certificate
        echo "Downloading certificate from $HOST_NAME..."
        # openssl s_client -servername $HOST_NAME -connect $HOST_NAME:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > temp.crt
        openssl s_client -showcerts -verify 5 -connect $HOST_NAME:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > temp.crt
      
        if [ -s "temp.crt" ]; then
        echo "Certificate downloaded successfully."
        else
        echo "Failed to download certificate."
        exit 1
        fi
      
        # Add the certificate to the keystore
        echo "Adding certificate to keystore '$KEYSTORE_PATH' with alias '$HOST_NAME'..."
        keytool -import -trustcacerts -alias "$HOST_NAME" -file "temp.crt" -keystore "$KEYSTORE_PATH" -noprompt
      
        if [ $? -eq 0 ]; then
        echo "Certificate added to keystore successfully."
        else
        echo "Failed to add certificate to keystore."
        fi
        rm temp.crt

build:
  stage: build
  extends: .maven
  script:
    - mvn $MAVEN_CLI_OPTS compile

  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/sdk-integration-tests/target
      - ${CI_PROJECT_DIR}/kount-ris-sdk/target
      - ${CI_PROJECT_DIR}/sdk-integration-tests/pom.xml
      - ${CI_PROJECT_DIR}/kount-ris-sdk/pom.xml
      - ${CI_PROJECT_DIR}/pom.xml

test:
  stage: test
  extends: .maven
  script:
    - mvn verify -e -Dsurefire.useFile=false -DRis.MerchantId=${RIS_SDK_SANDBOX_MERCHANT_ID} -DRis.API.Key=${RIS_SDK_SANDBOX_API_KEY} -Dkount.config.key=$(echo ${RIS_CONFIG_KEY_BASE64} | openssl base64 -d)
    - mvn jacoco:report
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/sdk-integration-tests/target/reports/jacoco-aggregate/jacoco.xml

test migration:
  stage: test
  extends: .maven
  script:
    - mvn verify -e -Dsurefire.useFile=false -DRis.MerchantId=${RIS_SDK_SANDBOX_MERCHANT_ID} -DRis.API.Key=${RIS_SDK_SANDBOX_API_KEY} -Dkount.config.key=$(echo ${RIS_CONFIG_KEY_BASE64} | openssl base64 -d) -Dmigration.mode.enabled=true -Dpayments.fraud.api.key=${PAYMENTS_FRAUD_API_KEY} -Dpayments.fraud.api.endpoint=${PAYMENTS_FRAUD_API_ENDPOINT} -Dpayments.fraud.auth.endpoint=${PAYMENTS_FRAUD_AUTH_ENDPOINT} -Dpayments.fraud.client.id=${PAYMENTS_FRAUD_CLIENT_ID}
    - mvn jacoco:report
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/sdk-integration-tests/target/reports/jacoco-aggregate/jacoco.xml
   
sonarqube scan:
  extends: .sq-scan
  stage: sonarqube scan
  allow_failure: true
  variables:
    SRC_EXCLUSIONS: "**/target/**,**/logs/**,**/bin/**,**/.m2/**,**/DS_Store/**,**/idea/**,**/*LICENSE,**/*.classpath,**/*.project,**/*.settings,**/*.gitignore,**/*.yml,**/test/**"
    JAVA_BINARIES_PATHS: "${CI_PROJECT_DIR}/kount-ris-sdk/target/classes/com/kount"
    JACOCO_COVERAGE_REPORT_PATHS: "${CI_PROJECT_DIR}/sdk-integration-tests/target/reports/jacoco-aggregate/jacoco.xml"

deploy:
  stage: deploy
  extends: .maven
  rules:
    - !reference [.rule-on-tag]
  script:
    - echo ${GPG_PASSPHRASE}
    - gpg $GPG_CLI_OPTS --passphrase ${GPG_PASSPHRASE} --import ./private_key_sender.asc
    - mvn --projects '!:sdk-integration-tests' $MAVEN_CLI_OPTS clean deploy -P release
